### ISSUE TITLE
webpages.espfs has zero size

### ISSUE THREAD

**Issue by MartinBielik** [OLIMEX/ESP8266#2]
Everything is prepared for flashing esphttpd example instead of webpages.espfs

**Comment by bobybc** [comment]
yes, the same for me - webpages.espfs is empty. please fix

**Comment by TsvetanUsunov** [comment]
this is not a problem as this file is rebuilds when you make flash it!

**Comment by bobybc** [comment]
Actually it was not built, until i chmod-ed the directory. It is something related to attributes of mkespfsimage\mkespfsimage

**Comment by MartinBielik** [comment]
Thi is the problem! In principle you should keep all binary files or none.
Reason why you should keep this files is that people can use windows utility for flashing (nodencu ...) without any linux configuration.
