### ISSUE TITLE
FOTA example

### ISSUE THREAD

**Issue by fvpalha** [OLIMEX/ESP8266#20]
Hi.

Do you have any FOTA example with [Unofficial Development Kit for Espressif ESP8266](https://github.com/CHERTS/esp8266-devkit) ?

Best regards.

**Comment by peter-valkov** [comment]
Currently we are using official SDK 1.3.0. I just saw that there is new 1.4.0 version and we will upgrade soon.

There is FOTA support in our IoT Firmware. You can check in user_config.c function config_firmware_handler() and user_flash.c

**Comment by fvpalha** [comment]
Thank you Peter.
