### ISSUE TITLE
ESP8266 as Eagle component

### ISSUE THREAD

**Issue by prasimix** [OLIMEX/ESP8266#29]
Before I do it myself, I'm wondering does anybody already create this module as an Eagle component (device/package/symbol) to use it in other Eagle projects?

**Comment by prasimix** [comment]
I made my own component. It's available [here](https://github.com/eez-open/eagle-libraries). Hopefully it's without any error, so you can close this issue.

**Comment by DanKoloff** [comment]
Thank you very much! I'm sure a lot of people would find the component of the whole MOD-WIFI-ESP8266-DEV board useful in their custom-made projects!

Best regards,
Lub/OLIMEX
