### ISSUE TITLE
Change Makefile or README for examples

### ISSUE THREAD

**Issue by erwinkendo** [OLIMEX/ESP8266#3]
Good Day

I was testing my MOD-WIFI-ESP8266-DEV module and when flashing I had an error because the makefile uses esptool.py default baudrate (115200) but the MOD-WIFI-ESP8266-DEV, or at leats the ones I got work at 58200 in UART mode. I am not issuing a pull request because I don't know how you would like to address this problem.

Kind regards

**Comment by yerpj** [comment]
If you add a parameter to your command, you should be able to use esptool.py with almost every baudrate:
`-b BAUDRATE`
for example : 

```
esptool.py COM15 -b 115200 read_mac
```
