### ISSUE TITLE
WEBCLIENT - no request freeing from list

### ISSUE THREAD

**Issue by mikexmas** [OLIMEX/ESP8266#30]
I encountered some problems while POSTing data using WEBCLIENT; I tried to send data to thingspeak.com in cloud (of course data format is different than Olimex event format), PUT and POST are supported, not websockets.
There is no request freeing from the list which may cause memory leak.
Thingspeak responds using chunked response (at least two messages for response), so for proper response handling its needed to collect all messages.
There is also trouble when to many requests is triggered, limitation of ESP library. In this case function "espconn_connect" returns error and no "webclient_connect" callback is fired - also no freeing of requests.

I fixed troubles in my for., commit: https://github.com/mikexmas/ESP8266/commit/4bfabe9c350430285199be070363cb6b4d9ca151

**Comment by peter-valkov** [comment]
Merged pull request
