### ISSUE TITLE
IoT Firmware: Default config settings after complete flashing

### ISSUE THREAD

**Issue by mikexmas** [OLIMEX/ESP8266#34]
When ESP is complete flashed (also blank.bin and esp_init_data_default.bin) there is different configuration of softAP & station which is stored by ESP SDK than when you press long button and restore_defaults occurs.

Is there a way to detect initial ESP settings in user_main to be overriden by restore_defaults (which works better)  not only with long-button press?

Best Regards

**Comment by peter-valkov** [comment]
Press the button and hold it for more than 5 secs. It will reset settings to IoT Firmware defaults.

**Comment by peter-valkov** [comment]
Here is the command I use for complete flash 

> esptool/esptool.py --baud 576000 write_flash 0x00000 bin/boot_v1.2.bin 0x01000 bin/upgrade/user1.2048.new.3.bin 0x81000 bin/upgrade/user2.2048.new.3.bin 0x1FC000 bin/esp_init_data_default.bin 0x1FE000 bin/blank.bin --flash_size 16m

**Comment by peter-valkov** [comment]
Note the last blank.bin at address 0x1FE000

**Comment by peter-valkov** [comment]
If you want to clear previous IoT Firmware settings as well you should flash with blank.bin at address 0x100000

**Comment by peter-valkov** [comment]
... so complete flash command should look like this:

> esptool/esptool.py --baud 576000 write_flash 0x00000 bin/boot_v1.2.bin 0x01000 bin/upgrade/user1.2048.new.3.bin 0x81000 bin/upgrade/user2.2048.new.3.bin 0x100000 bin/blank.bin 0x1FC000 bin/esp_init_data_default.bin 0x1FE000 bin/blank.bin --flash_size 16m

**Comment by peter-valkov** [comment]
After update to SDK 1.5.1 and new bootloader version 1.5 complete firmware flash command should look like:

> esptool/esptool.py --baud 576000 write_flash 0x00000 bin/boot_v1.5.bin 0x01000 bin/upgrade/user1.2048.new.3.bin 0x81000 bin/upgrade/user2.2048.new.3.bin 0x100000 bin/blank.bin 0x1FC000 bin/esp_init_data_default.bin 0x1FE000 bin/blank.bin --flash_size 16m

@mikexmas if this solves your problem let me know so we can close this issue.

Best Regards
Peter
