### ISSUE TITLE
What's the purpose of bringing out SD_CLK to SD_CMD? (EVB board)

### ISSUE THREAD

**Issue by atrent** [OLIMEX/ESP8266#36]
The EVB board brings out (on the board header) the GPIO 6 to 11 (SD_CLK to SD_CMD) but, if I understand correctly, they cannot be used without crashing the running program.
Am I wrong? Can they be used someway?
Thanks

**Comment by peter-valkov** [comment]
The short answer is: these pins can not be used. The way to do it is to unsolder the on-board flash memory (but you will not be able to execute programs from flash). You can either place your own flash memory or boot from SPI.
