### ISSUE TITLE
RX and TX pin are messed up  

### ISSUE THREAD

**Issue by ghost** [OLIMEX/ESP8266#44]
In the **ESP8266EX-how-to-update-firmware.pdf** you write:

> The connections are easier if the board has male UEXT connector (like ESP8266-EVB). The important part
> here is to connect the GND of the cable to the GND pin (#2) of the UEXT connector. Then TXD of the 
> cable to RXD of the UEXT (#4). Finally, RXD of the cable to TXD of the UEXT (#3). 

but in the board's schematic , **MOD-WIFI-ESP8266-DEV, hardware revision  A and B**, UEXT-PIN-4 is connected to TXD and UEXT-PIN-3 is connected to RXD. 
So you have already crossed the RX-TX in your boards. 
Please provide a correct description because there is a confusion.

**Comment by DanKoloff** [comment]
Hey,

Thanks for the notice. I've now clarified it in the document.

The picture shows female connector as in ESP8266-EVB and ESP8266-EVB-BAT. These boards are meant to act as main "host" boards.

However, the modules that you mentioned MOD-WIFI-ESP8266-DEV are meant to have male (not female) connector. They are meant to act as slave "device" boards that get attached to main "host" boards with female connector. RX and TX are swapped in these male connectors - so when you connect such a slave to a main board you would have a working data UART.

Best regards,
Lub/OLIMEX
