### ISSUE TITLE
it is possible to add webserver/websocket port config in web app

### ISSUE THREAD

**Issue by toome123** [OLIMEX/ESP8266#45]
It will usefull to add way to change default port from 80 to another one... Becuase host server/IoT server in some cases may use it for another app and board is not able to connect..

**Comment by peter-valkov** [comment]
I guess you mean IoT server configuration?

**Comment by toome123** [comment]
Yes, IoT configuration.

**Comment by peter-valkov** [comment]
Next week I will see what can be done

**Comment by peter-valkov** [comment]
Done ae505fbbc79e58adb1ca0ff17edd8fef9ab8013f

**Comment by toome123** [comment]
Благодаря
