### ISSUE TITLE
WPA2-PEAP Support

### ISSUE THREAD

**Issue by gorghino** [OLIMEX/ESP8266#47]
Hi :)
Did you success in connecting to a WPA2-PEAP with the new sdk V2.0.0?
I'm following Gidrix's sketch (https://github.com/esp8266/Arduino/issues/2595) that it follows SDK Documentation flow, but my ESP8266-07 doesn't connect to eduroam (WPA-PEAP MSCHAPv2 network).

**Comment by peter-valkov** [comment]
I never used WPA2-PEAP. Usually I use WPA2-PSK.
