### ISSUE TITLE
Status/event Messages: field "device" to fill with host name

### ISSUE THREAD

**Issue by mikexmas** [OLIMEX/ESP8266#48]
Currently status/events messages has device field constant ESP8266, which means nothing:
{"Device" : "ESP8266", "Status" : "Authorization success"}

I suggest to put in some usefiull information, like hostname:
{"Device" : "LivingRoomThing", "Status" : "Authorization success"}
maybe wifi_station_get_hostname()

I've made a simple OpenHub binding and hostname gives much more information than constant.

**Comment by peter-valkov** [comment]
It has a meaning when you have more then one device/module attached. The ESP8266 device is used for generic messages. Each device uses its own name. 

For example I have setup with MOD-TC-MK2 and 6 x MOD-LED8x8RGB as array all connected to ESP8266-EVB via UEXT. So I'm receiving messages like 

```
{"Device" : "ESP8266", "Status" : "Authorization success"}
{"Device": "MOD-LED8x8RGB", "Status": "OK","Data": { "cols": 6, "rows": 1, "Speed": 85, "R": 0, "G": 1,"B": 0, "Text": "October 27 17:07 Thursday" }}
{"Device" : "MOD-TC-MK2", "Status" : "OK", "Data" : {"Temperature" : 23.93}, "I2C_Address" : "0x23"}
{"Device" : "MOD-LED8x8RGB", "Status" : "Done"}
```

As you can see different devices send different **Data** object. And the value of **Device** field is used to distinguish what kind of data can be found in **Data** object

Hope that this makes sense to you.
