### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by mtailanian** [OLIMEX/ESP8266#49]
Hi, hello,
I´m trying to compile your code, but I´m getting some trouble while executing "make" command.
Here is the output:

xt-xcc -Os -g -Wpointer-arith -Wundef -Werror -Wl,-EL -fno-inline-functions -nostdlib -mlongcalls -mtext-section-literals -ffunction-sections -fdata-sections -fno-builtin-printf  -DICACHE_FLASH -DFREERTOS -DOTA_FLASH_SIZE_K=32768 -DOTA_TAGNAME="\"generic\""  -I include -I ./ -I ../include \-I ../libesphttpd/include -I ../libesphttpd/espfs 	 -I ../include -I ../include/eagle -I ../driver_lib/include  -o .output/eagle/debug/obj/cgi-test.o -c cgi-test.c
/bin/sh: xt-xcc: command not found
make[1]: *** [.output/eagle/debug/obj/cgi-test.o] Error 127
make: *** [.subdirs] Error 2

Any hint will be really appreciated! 

Thanks in advance!

**Comment by peter-valkov** [comment]
```
/bin/sh: xt-xcc: command not found
```
looks like you did not install esp8266 toolchain
